### ISSUE TITLE
Duration is not retrieved

### ISSUE THREAD

**Issue by bevrard** [webdriverio/recorder-extension#9] opened 2022-09-30 11:48 UTC
When I use the duration parameter in Chrome Recorder, I'm not able to get this parameter when I export the Webdriver script.

Is there a solution for that?

Regards

**Comment by christian-bromann** [comment] 2022-09-30 15:59
Duplicate of webdriverio/chrome-recorder#2

**Closed by christian-bromann** 2022-09-30 15:59 UTC
